### ISSUE TITLE
Failed to activate the status-bar-blame package

### ISSUE THREAD

**Issue by tbhaa** [baldurh/atom-status-bar-blame#4]
[Enter steps to reproduce:]

Fails on startup. Started seeing this after last update (not the one from today 19 april, but the one before that). 

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [status-bar-blame](https://github.com/baldurh/atom-status-bar-blame) package 1.0.3

### Stack Trace

Failed to activate the status-bar-blame package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'status-bar-blame'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'status-bar-blame'. A type with that name is already registered.
    at Error (native)
    at /packages/status-bar-blame/lib/blame-status-bar-view.js:158:25)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/status-bar-blame/lib/init.js:9:27)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-status-bar-blame 1.0.0 
gruvbox-plus-syntax 1.3.1 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.57.3 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
nuclide 0.217.0 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
status-bar-blame 1.0.3 
tool-bar 1.1.0 
```

**Comment by tbhaa** [comment]
Uninstall, restart, re-install fixed it this time. Tried it a few days ago but it did not work then, but today it worked. Maybe updated Atom helped.

**Comment by baldurh** [comment]
Hi! You’re obviously one of the early adopters of this package 😄 The thing is that I renamed the package from `atom-status-bar-blame` to `status-bar-blame` because it seems to be the trend to not include atom in the name of atom packages. So at one point you had both versions installed. You can see them both in the list.

Thanks for posting. Sorry for not responding sooner. GitHub isn’t sending me any notifications ☹️ 
And sorry for the inconvenience.
